// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(TrafficAccidentsDbContext))]
    [Migration("20230806125838_AddTrafficAccidentsTable")]
    partial class AddTrafficAccidentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Database.Entities.TrafficAccidentDataModel", b =>
                {
                    b.Property<Guid>("TrafficAccidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("traffic_accident_id");

                    b.Property<Point>("AccidentLocation")
                        .IsRequired()
                        .HasColumnType("geography (point)")
                        .HasColumnName("accident_location");

                    b.Property<int>("AccidentType")
                        .HasColumnType("integer")
                        .HasColumnName("accident_type");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalTrafficAccidentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("external_traffic_accident_id");

                    b.Property<int>("ParticipantsNominalCount")
                        .HasColumnType("integer")
                        .HasColumnName("participants_nominal_count");

                    b.Property<int>("ParticipantsStatus")
                        .HasColumnType("integer")
                        .HasColumnName("participants_status");

                    b.Property<string>("PoliceDepartment")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("police_department");

                    b.Property<DateTime>("ReportedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_on");

                    b.HasKey("TrafficAccidentId")
                        .HasName("pk_traffic_accidents");

                    b.HasIndex("PoliceDepartment")
                        .HasDatabaseName("ix_traffic_accidents_police_department");

                    b.ToTable("traffic_accidents");
                });
#pragma warning restore 612, 618
        }
    }
}
